"""Pure construction of the bounded localization telemetry record."""

from __future__ import annotations

from typing import Any


RESULT_FIELDS = (
    "timing_clock",
    "client_submit_mono",
    "client_dequeue_mono",
    "client_write_start_mono",
    "client_write_done_mono",
    "worker_read_done_mono",
    "worker_core_start_mono",
    "worker_core_done_mono",
    "client_response_mono",
    "ui_arrival_mono",
    "frame_callback_enter_mono_ns",
    "frame_preprocess_start_mono_ns",
    "frame_yuv_ready_mono_ns",
    "frame_preprocess_done_mono_ns",
    "frame_store_mono_ns",
    "ui_serialize_start_mono_ns",
    "ui_serialize_done_mono_ns",
    "client_submit_mono_ns",
    "client_dequeue_mono_ns",
    "client_write_start_mono_ns",
    "client_write_done_mono_ns",
    "worker_read_done_mono_ns",
    "worker_core_start_mono_ns",
    "worker_core_done_mono_ns",
    "client_response_mono_ns",
    "ui_arrival_mono_ns",
    "ui_serialize_ms",
    "client_queue_wait_ms",
    "client_pipe_write_ms",
    "submit_to_worker_read_ms",
    "worker_done_to_client_ms",
    "client_roundtrip_ms",
    "ui_poll_delay_ms",
    "e2e_submit_to_ui_ms",
    "source_frame_stamp_mono",
    "source_stamp_semantics",
    "hold_retry",
    "hold_kind",
    "source_stamp_age_at_submit_ms",
    "source_stamp_age_at_ui_ms",
    "callback_to_preprocess_start_ms",
    "yuv_view_ms",
    "frame_preprocess_ms",
    "preprocess_done_to_submit_ms",
    "callback_to_submit_ms",
    "callback_to_inference_start_ms",
    "callback_to_localization_done_ms",
    "callback_to_ui_ms",
    "gpu_span_ms",
    "gpu_timing_profiled",
    "tracker_variant",
    "display_seq",
    "pose",
    "pose_raw",
    "pose_filter",
    "vpr_ms",
    "feature_ms",
    "match_ms",
    "pnp_ms",
    "mode",
    "next_mode",
    "composite_stage",
    "inliers",
    "n_corr",
    "reference_count",
    "requested_reference_count",
    "staged_early_stop",
    "rejected",
    "limited_jump",
    "candidate_mode",
    "global_retrieval_calls",
    "reproj_rms",
    "inlier_ratio",
    "inlier_grid_cells",
    "neuflow_stage",
    "neuflow_anchor_count",
    "neuflow_flow_ms",
    "neuflow_gpu_ms",
    "projection_fallback",
    "projection_reason",
    "projection_radius_px",
    "projection_anchor_count",
    "projection_visible_count",
    "projection_match_count",
    "projection_best_inliers",
    "projection_project_ms",
    "projection_feature_ms",
    "projection_match_ms",
    "frame_name",
    "error",
    "force_track_bench",
    "force_track_label",
    "force_track_ref_requested",
    "force_track_ref_resolved",
    "force_track_seed_ms",
    "benchmark_mode_requested",
    "benchmark_mode_active",
    "relocalize_requested",
    "confidence_low",
    "confidence_hold_event",
    "confidence_hold_active",
    "confidence_low_streak",
    "confidence_hold_attempts",
    "benchmark_prior_kind",
    "benchmark_prior_ref",
    "benchmark_setup_ms",
    "benchmark_seeded",
)


def build_localization_metric_record(
    result: dict[str, Any],
    *,
    metric_mono_ns: int,
    loc_fps: float,
    submit_ok: int,
    submit_skip_busy: int,
    submit_busy_attempts: int,
) -> dict[str, Any]:
    """Copy only the stable telemetry contract and add UI-side counters."""
    record = {
        "t_mono": metric_mono_ns * 1e-9,
        "t_mono_ns": metric_mono_ns,
        "success": bool(result.get("success")),
        "wall_ms": result.get("wall_ms"),
        "core_wall_ms": result.get("core_wall_ms", result.get("wall_ms")),
    }
    record.update((field, result.get(field)) for field in RESULT_FIELDS)
    record.update(
        {
            "limited_jump_confirmed": result.get("limited_jump_confirmed", False),
            "loc_fps": round(loc_fps, 3),
            "submit_ok": submit_ok,
            "submit_skip_busy": submit_skip_busy,
            "submit_busy_attempts": submit_busy_attempts,
        }
    )
    return record
